Update syntax for loginInBackground example
ParsePlatform/Docs pull request #387
Opened 2016-11-21 10:50 UTC by jaimeagudo

2016-11-21 12:36 UTC, flovilmart commented
The existing code should correctly work in swift. Why that change?

2016-11-25 16:04 UTC, nitrag commented
@jaimeagudo Is correct. I would go as far as to include the error parsing, which was quite difficult to figure out on my own.

```
PFFacebookUtils.logInInBackground(withReadPermissions: ["public_profile","email"]) {
            (user: PFUser?, error: Error?) -> Void in
            if let error = error {
                if let errorString = (error as NSError).userInfo["error"] as? String {
                    NSLog(errorString);
                }
            } else {
                if let user = user {
                    if user.isNew {
                        print("User signed up and logged in through Facebook!")
                    } else {
                        print("User logged in through Facebook!")
                    }
                    self.currentUser = PFUser.current();
                    self.loggedIn()
                }
            }
        }
```

2016-11-25 16:12 UTC, flovilmart requested changes

2016-11-25 16:12 UTC, flovilmart commented on _includes/ios/users.md
> +  if let u = user {
revert that change please

2016-11-25 16:12 UTC, flovilmart commented on _includes/ios/users.md
> +    if u.isNew {
that one too.

2017-04-19 06:28 UTC, jaimeagudo commented on _includes/ios/users.md
> +    if u.isNew {
That's the current syntax and _Intellisense_ in Xcode is *&^#, why do you want to revert it?

2017-04-19 11:28 UTC, flovilmart commented on _includes/ios/users.md
> +    if u.isNew {
we prefer `let user = user` usually

2018-04-14 14:39 UTC, addisonElliott commented
Was looking through the code, and I fail to see where logInInBackground is defined for PFFacebookUtils? Where is the code at?

2018-04-14 15:20 UTC, flovilmart commented
@addisonElliott https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/ParseFacebookUtils/ParseFacebookUtils/PFFacebookUtils.h#L74

2019-03-09 21:21 UTC, Tom-Fox1 commented
As this is dormant I have merged #589 which fixes the syntax with respect to the suggested changes here.

2019-03-09 21:21 UTC, closed without merging