Update Init for Facebook
ParsePlatform/Docs pull request #389
Opened 2016-11-25 19:26 UTC by nitrag

Updating for swift 3

2016-11-26 16:52 UTC, nitrag commented
Signed CLA.

2016-11-28 16:40 UTC, hramos requested changes

2016-11-28 16:40 UTC, hramos commented on en/ios/users.mdown
> +func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -&gt; Bool {
Is &gt; necessary here? It should render fine within the code block, and it looks like you didn't need to use this encoding later in the same file.

2019-03-08 11:59 UTC, Tom-Fox1 commented
I'm sorry that this has been over looked. Would you be able to update this code for swift 4.2 (+ the latest version of the Parse iOS SDK) and then I will take another look?

Also would you be able to remove the vertical parameter alignment as it doesn't appear well on the docs:
<img width="639" alt="screenshot 2019-03-08 at 11 58 12" src="https://user-images.githubusercontent.com/13188249/54027439-74fc3c00-4199-11e9-997e-9ec42817b805.png">

2019-03-12 22:02 UTC, Tom-Fox1 commented
I'm closing this now as I have started a new pull request that brings in these changes (those of which are still needed).

2019-03-12 22:02 UTC, closed without merging