Rest Doc for Full Text Search and withinPolygon
ParsePlatform/Docs pull request #444
Opened 2017-06-14 05:28 UTC by dplewis

Parse Server has been updated with new features.

See
https://github.com/parse-community/parse-server/pull/3866
https://github.com/parse-community/parse-server/pull/3904

2017-06-14 11:32 UTC, flovilmart requested changes
A few typos here and there otherwise it's looking great!
Can you also mention that each feature is available only starting Parse-server 2.5.0?

2017-06-14 11:32 UTC, flovilmart commented on _includes/rest/queries.md
> +Note: Postgres doesn't support `$caseSensitive` for Full Text Search, please use $regex above or create a lowercase column in your DB. Postgres supports `$diacriticSensitive: true` by default but `$d
Typo: undate

2017-06-14 11:32 UTC, flovilmart commented on _includes/rest/queries.md
> +Note: Postgres doesn't support `$caseSensitive` for Full Text Search, please use $regex above or create a lowercase column in your DB. Postgres supports `$diacriticSensitive: true` by default but `$d
Typo: Extention

2017-06-14 11:32 UTC, flovilmart commented on _includes/rest/queries.md
> +Please refer to your database documentation on Full Text Search to setup your indexes, weights and limitations.
Can you put the links to those documentation for mongo 3.2 or 3.4 and PG?

2017-06-14 15:07 UTC, dplewis commented on _includes/rest/queries.md
> +Note: Postgres doesn't support `$caseSensitive` for Full Text Search, please use $regex above or create a lowercase column in your DB. Postgres supports `$diacriticSensitive: true` by default but `$d
nice catch

2017-06-14 22:01 UTC, dplewis commented on _includes/rest/queries.md
> +Please refer to your database documentation on Full Text Search to setup your indexes, weights and limitations.
Done

2017-08-30 02:38 UTC, felipemartim commented
Is this still going to be merged? 👍

2017-09-08 01:05 UTC, montymxb commented
@felipemartim yes! 
@flovilmart changes look good to you?

2017-09-08 02:12 UTC, flovilmart approved these changes

2017-09-08 02:13 UTC, flovilmart commented
This. Is. Awesome!

2017-09-08 02:13 UTC, merged