First pass at read preference
ParsePlatform/Docs pull request #449
Opened 2017-06-27 19:05 UTC by acinader

1. just getting started, will need to be adjusted when we make client accessible
2. are there more examples I should add??

2017-06-27 19:06 UTC, acinader commented
@davimacedo please take a look.  anything we can add here??

2017-06-28 05:42 UTC, davimacedo commented
I think it is only missing the includeReadPreference option

2017-07-03 01:24 UTC, flovilmart requested changes

2017-07-03 01:24 UTC, flovilmart commented on assets/js/bundle.js
> +/***/ (function(module, exports, __webpack_require__) {
not sure this should be committed.

2018-10-16 22:43 UTC, acinader commented
@flovilmart

2018-10-16 22:44 UTC, flovilmart approved these changes

2018-10-16 22:55 UTC, merged