Update push-notifications.md
ParsePlatform/Docs pull request #452
Opened 2017-07-05 00:04 UTC by jeacott1

modify docs to show support for: "Increment `badge` under `data` for iOS badge number"

2017-07-05 00:22 UTC, flovilmart requested changes

2017-07-05 00:22 UTC, flovilmart commented on _includes/parse-server/push-notifications.md
> +* Increment `badge` under `data` for iOS badge number
Ut’s Also supported on android now :)

2017-07-05 03:36 UTC, jeacott1 commented on _includes/parse-server/push-notifications.md
> +* Increment `badge` under `data` for iOS badge number
Ut?

2017-07-05 03:47 UTC, flovilmart commented on _includes/parse-server/push-notifications.md
> +* Increment `badge` under `data` for iOS badge number
It...

2017-07-27 15:55 UTC, flovilmart approved these changes

2017-07-27 15:56 UTC, merged