Changes references to api.parse.com and /1/
ParsePlatform/Docs pull request #458
Opened 2017-07-28 18:03 UTC by montymxb

The current [REST Guide](http://docs.parseplatform.org/rest/guide/#quick-reference) and parts of the other guides contain numerous references to the now inactive `api.parse.com`, and the old `/1/` version 1 mount path. As it stands this is misdirecting some individuals, as seen in [#694](https://github.com/parse-community/Parse-SDK-Android/issues/694) over in the Android sdk. 

This proposes to change those old links into `YOUR.PARSE-SERVER.HERE` and `/parse/` respectively. This also adjusts the initial wording for the [REST Quick Reference](https://github.com/montymxb/docs/blob/506928730bdb98949115705bdeb3bb4c64fd1c84/_includes/rest/quick-reference.md) section to remind the user that in the examples provided they should add their own domain, their own mount path and to consider whether they should be accessing over HTTP/HTTPS.

2017-07-28 19:12 UTC, flovilmart commented
Would it be insane to make it dynamic?

2017-07-28 22:03 UTC, montymxb commented
Umm possibly. Do you mean as in they would enter their own domain/mount path and all of the examples would populate as such?

2017-07-29 01:04 UTC, montymxb commented
@flovilmart looking back at it there's a few hundred references roughly, primarily in the REST guide but also dotted in the other sdk guides as well. Adding in a feature to set their own server url & mount path would require tracking all of those, in addition to setting up the JS to update and editable fields to track those updates.

It could be done if there's an interest in it. But I'll have to go back and set something up.

2017-07-29 04:47 UTC, montymxb commented
Added in the ability to set your own server/mount shown on the page. For the other guides they just contain a handful of references, and the server settings takes up space on the side nav bar, so I'm just leaving it out from everything besides the **REST** guide. Makes sense to have it there anyways since all the refs there were changed primarily.

Quick note this also makes a quick change to some css that wasn't quite right from #457. Additionally I moved a change for platform extraction from #443  into **_app/main.js**. I missed it the first time around but that change was made in **assets/js/bundle.js**, which is built up from the former file. If the site were to be rebuilt before it was republished those changes would be erased.

@flovilmart can you take a look at this and give me your thoughts on it? It's tinkering with the sidebar, so I want to be sure this is acceptable before we move this along.

2017-07-29 09:24 UTC, flovilmart requested changes
A few missing spots but I believe this should work on paper! That’s wonderful otherwise :)

I’ll try it today :)

2017-07-29 09:24 UTC, flovilmart commented on _includes/android/push-notifications.md
> +https://YOUR.PARSE-SERVER.HERE/parse/installations
Here?

2017-07-29 09:24 UTC, flovilmart commented on _includes/android/push-notifications.md
> +https://YOUR.PARSE-SERVER.HERE/parse/installations
Here?

2017-07-29 09:24 UTC, flovilmart commented on _includes/arduino/other.md
> +ParseResponse response = Parse.sendRequest("POST", "/parse/users", "{\"username\":\"cooldude6\",\"password\":\"p_n7!-e8\"}", "");
Here?

2017-07-29 16:39 UTC, montymxb commented
Ahh, find and replace wasn't nearly as good as I thought it was...one moment, I'll tidy those extra ones up.

2017-07-29 16:50 UTC, montymxb commented
Thought I initially missed some find and replaces or something, but yeah those spots have been left out of the 'switching' intentionally. In the other guides there was only sparing use of `api.parse.com` and using `/1/`. Adding in the custom server/mount functionality there would be taking up that extra navbar space for only changing a handful of lines in an entire guide :/. Not sure how assistive it would be if the user would have to hunt just to find the few references it changes.

I'm figuring with it just on the REST guide that's about 90% of our api references, everything else is just a sprinkling of curl refs and the one mention per guide for initializing that sdk. For the extra space it takes up on the left it would seem to have the most direct benefit there.

2017-07-29 16:56 UTC, montymxb commented
This just occurred to me, should we add a toggle for protocol, i.e. a drop down for **http**/**https** to further adjust the relevant examples? In quite a few cases where someone is learning it's likely they may just be testing on localhost.

2017-07-29 17:15 UTC, montymxb commented
Okay this is a bit of a jump, but perhaps we can get this on all pages, and in a less intrusive fashion, by making it an expanding section of sorts. If sidebar space is of no consequence then maybe we look into fleshing this out to fully configure with that http/https toggling. 

It would be even _cooler_ to have additional substitution for keys too, like **appId**, **masterKey**, etc. Normally this would be ok as the JS is client side, so no information would be sent across the wire. However the docs are not served securely, so there's no guaranteeing the content on the page hasn't been modified in a malicious fashion, i.e. malicious JS injected by a MITM scraping inserted keys or something like that :/. Still it's food for thought, if we ever got a cert somehow via letsencrypt or something we could get a little bit fancier with this.

2017-07-29 17:59 UTC, flovilmart commented
If we put the selection in a reusable section in the header that could work as well? AppIiD and client key would be ok to inject as public, perhaps we could store those in the local data store for reuse. I like that it’s JS dépendant and still renders OK without JS

2017-07-29 18:49 UTC, montymxb commented
We can do that. I also realized that the mobile version for smaller screens won't have the sidebar as it becomes a drop down instead, which is just a `<select>` element. To make sure this shows up on mobile (and is reusable) I went ahead and modified it to be a separate section under `common`, which can be added right before the `Get Started` section. A bit cleaner and more manageable that way, and we can add as many customizable fields as we like.

I'll see what I can do about those public key fields, now that this is moving into it's own 'customization' section we can expand it however we like without filling up the sidebar 👍 .

And yeah I can toss those into the local storage to persist across page loads, that would be much more convenient.

2017-09-27 15:11 UTC, montymxb commented
@flovilmart are we still interested in pursuing this?

2017-09-27 15:19 UTC, flovilmart commented
Sorry, I need to jump back on that!

2017-09-27 15:22 UTC, montymxb commented
No rush, just should make a note to get back to this at some point.

2017-10-08 19:07 UTC, flovilmart commented
It's beautiful!

2017-10-08 19:07 UTC, flovilmart approved these changes

2017-10-08 19:07 UTC, merged

2017-10-11 18:53 UTC, montymxb commented
@flovilmart just wanted to say now that this in now we can see what people think of the fields customization in the [REST Guide](http://docs.parseplatform.org/rest/guide/). The other /1/ marks are changed, but just the REST guide has the new customization feature. I imagine if it's working okay I can add a PR later on to add it to other guides, if anyone calls for it.

2017-10-11 19:10 UTC, flovilmart commented
that's good for the rest, perhaps we need a reset, button, I had trouble reverting to the original values

2017-10-11 19:13 UTC, montymxb commented
Oh, that would be nice. I'll make a note to put up a PR for a reset button.

2017-10-11 19:37 UTC, flovilmart commented
Haha thanks!