Add Android Polygon and Full Text
ParsePlatform/Docs pull request #499
Opened 2018-01-20 00:46 UTC by dplewis

Closes: https://github.com/parse-community/docs/issues/466

I also fixed some aggregate rest docs.

2018-01-20 02:45 UTC, dplewis commented
@montymxb Can you look this over?

2018-01-20 23:27 UTC, montymxb commented on _includes/android/geopoints.md
> +To retrieved `ParseGeoPoint` from an object
typo:
> To retrieve

2018-01-20 23:27 UTC, montymxb commented on _includes/android/geopoints.md
> +To retrieved `ParseGeoPoint` from an object
Could add some punctuation at the end of `object` as well.

2018-01-20 23:29 UTC, montymxb commented on _includes/android/geopoints.md
> +To retrieved `ParsePolygon` from an object
typo:
> To retrieve
Punctuation after `object` as well.

2018-01-20 23:31 UTC, montymxb commented on _includes/android/queries.md
> +* Parse Server 2.5.0+
Should state
> **Requires** Parse Server 2.5.0+

2018-01-20 23:34 UTC, montymxb requested changes
Just a few typos, stylistic suggestions. Rest looks good.

2018-01-21 00:08 UTC, dplewis commented
@montymxb Changes made

2018-01-21 00:13 UTC, montymxb requested changes
Still those 2 things, should be good after that.

2018-01-21 00:13 UTC, montymxb commented on _includes/android/geopoints.md
> +To retrieved `ParseGeoPoint` from an object.
Still need to correct **retrieved** to **retrieve**. To improve the wording could be
> To **retrieve a** `ParseGeoPoint` from an object.

2018-01-21 00:13 UTC, montymxb commented on _includes/android/geopoints.md
> +To retrieved `ParsePolygon` from an object.
same thing here.

2018-01-21 00:35 UTC, montymxb approved these changes
Awesome :octocat: , we're all good!

2018-01-21 00:49 UTC, dplewis commented
Sweet!

2018-01-22 04:07 UTC, merged