Add docs for passing masterKey to user._linkWith
ParsePlatform/Docs pull request #611
Opened 2019-03-29 22:14 UTC by acinader

2019-03-29 22:14 UTC, acinader commented
@Tom-Fox1 fyi

2019-03-29 22:20 UTC, dplewis requested changes

2019-03-29 22:20 UTC, dplewis commented on _includes/js/users.md
>  user._linkWith("facebook", {}).then(function(user){
`user._linkWith("facebook", {})` I don't think this works.

should be replaced with `_unlinkFrom`

2019-03-29 22:20 UTC, dplewis commented on _includes/js/users.md
> +const loggedIn = await Parse.User.logInWith('CustomAdapter', myAuthData);
An example of CustomAdapter, server config and _registerProvider should be included.

2019-04-13 21:50 UTC, TomWFox approved these changes
I fixed the link to the 3rd party auth section in the server guide.

I can't comment on the code but the wording looks good to me!

2019-04-13 22:08 UTC, dplewis commented
Good catch!

2019-04-13 22:08 UTC, merged