Add `keys` and `excludeKeys` options to REST docs
ParsePlatform/Docs pull request #649
Opened 2019-07-25 06:07 UTC by RaschidJFR

2019-07-26 21:16 UTC, TomWFox commented
Thanks for doing that, I will review this tomorrow.

2019-07-27 10:55 UTC, TomWFox requested changes
JS changes look good 👍

I don't think `excludeKeys` should be mentioned in the retrieving objects section in the REST guide. If you look at the [query constraints](http://docs.parseplatform.org/rest/guide/#query-constraints) section there is a part which would make more sense...
> In addition to where, there are several parameters you can use to configure what types of results are returned by the query.

I think `excludeKeys` should be added in the table here after `keys` and an example added after the `keys` example.

2019-07-28 02:15 UTC, RaschidJFR commented
You're right  @TomWFox ! I let `include` deceive me. BTW I also added padding to `td` elements as tables started to look a bit tight.

2019-07-28 09:41 UTC, TomWFox approved these changes
Looks good, tables look much better!

2019-07-28 09:42 UTC, TomWFox commented
@dplewis could you give the code samples a quick once over?

2019-07-28 15:06 UTC, dplewis requested changes
Looks good to me. Just a quick nit

2019-07-28 15:06 UTC, dplewis commented on _includes/rest/queries.md
> +| excludeKeys   | Exlcude specific fields from the returned query   |
Typo *Exclude specific fields...

2019-07-28 15:26 UTC, merged