GraphQL Customisation
ParsePlatform/Docs pull request #652
Opened 2019-07-29 12:00 UTC by omairvaiyani

This is a guide for the [GraphQL Config feature](https://github.com/parse-community/parse-server/pull/5782) but I have placed it under the header "Customisation". I think this would be an appropriate place to also add docs for this [PR](https://github.com/parse-community/parse-server/pull/5821)

2019-07-29 13:42 UTC, TomWFox requested changes
Looks good, thanks for taking the time to do this! Just a few changes I can see immediately.

2019-07-29 13:42 UTC, TomWFox commented on _includes/graphql/customisation.md
> +We have provided a public API in ```ParseGraphQLServer``` which accepts the above JSON object for setting (and updating) your Parse GraphQL Configuration, ```setGraphQLConfig```:
Should be single backticks

2019-07-29 13:42 UTC, TomWFox commented on _includes/graphql/customisation.md
> +By default, all of your Parse classes, including the defaults such as ```Parse.User```, ```Parse.Session```, ```Parse.Role``` are added to the schema. You can restrict this using the ```enabledForCla
```suggestion
By default, all of your Parse classes, including the defaults such as ```Parse.User```, ```Parse.Session```, ```Parse.Role``` are added to the schema. You can restrict this using the ```enabledForClassess``` or ```disabledForClassess`` options, which accepts an array of class names.
```

2019-07-29 13:42 UTC, TomWFox commented on _includes/graphql/customisation.md
> +By default, we enrich the schema by generating a number of [Input Types](https://graphql.org/learn/schema/#input-types) for each class. This, as a healthy side-effect improves development experience
```suggestion
By default, we enrich the schema by generating a number of [Input Types](https://graphql.org/learn/schema/#input-types) for each class. This, as a healthy side-effect, improves development experience by providing type-completion and docs, though the true purpose is to define exactly what fields are exposed and useable per operation type. You can provide a ```type``` setting for any or each of your classes to limit which fields are exposed:
```

2019-07-29 13:47 UTC, TomWFox requested changes
This new section needs to be added to the [graphql.md](https://github.com/parse-community/docs/blob/gh-pages/graphql.md) file so that it is added to the guide when the docs are built.

2019-07-29 23:21 UTC, davimacedo requested changes
Thanks for the PR! I like the way you explained. Additionally to @TomWFox comments, I added some other few suggestions. The rest seems good to me.

2019-07-29 23:21 UTC, davimacedo commented on _includes/graphql/customisation.md
> +```typescript
can you change to javascript?

2019-07-29 23:21 UTC, davimacedo commented on _includes/graphql/customisation.md
> +```json
It is not a valid json and it will probably be `red` when rendered. Can you please use javascript for this one and actually all others?

2019-07-29 23:21 UTC, davimacedo commented on _includes/graphql/customisation.md
> +      constraintFields: ["name", "age"],
it should be inside `type: {}` right?

2019-07-30 08:24 UTC, omairvaiyani reviewed
Added all the suggestions from above - @davimacedo I've switched everything to javascript except [line 16](https://github.com/parse-community/docs/pull/652/files#diff-2f28f36517e0808530394fe235fd3a00R13) given that it's using the `interface` structure.

2019-07-30 08:32 UTC, davimacedo approved these changes
It looks good to me

2019-07-30 10:25 UTC, TomWFox approved these changes

2019-07-30 10:25 UTC, merged