Parse.Cloud.onLiveQueryEvent Documentation
ParsePlatform/Docs pull request #666
Opened 2019-08-14 20:36 UTC by dplewis

closes: https://github.com/parse-community/docs/issues/628

I plan on adding more parameters on the server like sessionToken and connectedAt timestamp.

If you can think of any other parameters / events that would help with monitoring I can open a PR with them

2019-08-14 20:53 UTC, TomWFox reviewed
Nice!

2019-08-14 20:53 UTC, TomWFox commented on _includes/cloudcode/cloud-code.md
> +Sometimes you may want monitor Live Query Event to be used with a 3rd Party such as datadog. The `onLiveQueryEvent` trigger can be logging events triggered, number of clients connected, number of sub
```suggestion
Sometimes you may want to monitor Live Query Events to be used with a 3rd Party such as datadog. The `onLiveQueryEvent` trigger can log events triggered, number of clients connected, number of subscriptions and errors.
```

2019-08-14 21:34 UTC, dplewis commented
@davimacedo Can any other features you can think of that we can add to this for better monitoring?

2019-08-14 22:03 UTC, davimacedo commented
I think it would be very helpful to have the client's `installationId`, `sessionToken`, and `usingMasterKey` in these events. I've seen some developers asking for them.

2019-08-16 01:57 UTC, dplewis commented
I opened a PR for improving this. https://github.com/parse-community/parse-server/pull/5927

I will update this PR and the Wiki after the next server release.

2019-09-12 22:55 UTC, dplewis commented
@TomWFox i forgot about this one. I already updated the Wiki. This should be good to go after the last release.

2019-09-13 12:59 UTC, TomWFox requested changes

2019-09-13 12:59 UTC, TomWFox commented on _includes/cloudcode/cloud-code.md
> +*client, sessionToken, useMasterKey and installationId are available on parse-server cloud code 2.8.0+*
3.8.0?
```suggestion
*client, sessionToken, useMasterKey and installationId are available on parse-server cloud code 3.8.0+*
```

2019-09-17 13:21 UTC, merged