added section about master key config
ParsePlatform/Docs pull request #667
Opened 2019-08-20 18:33 UTC by mtrezza

2019-08-20 22:05 UTC, TomWFox requested changes
Wow fast, I love when the docs are ready even before the feature has been merged or released!

I think a bit of rewording is needed here, we'll wait to merge this until the relevant PRs have been merged and releases made.

2019-08-20 22:05 UTC, TomWFox commented on _includes/cloudcode/cloud-code-advanced.md
> +By default, a parameter can be retrieved by clients which may not be desired if the parameter contains sensitive information that should not be exposed to clients. A parameter can be made retrievable
```suggestion
By default, Parse Config parameters can be publicly read which may be undesired if the parameter contains sensitive information that should not be exposed to clients. A parameter can be made readable only with the master key by setting the `Master Key Only` property via the Parse Dashboard to `true`. 
```

2019-08-20 23:32 UTC, mtrezza commented
Requires https://github.com/parse-community/parse-server/pull/5954 and https://github.com/parse-community/parse-dashboard/pull/1233 to be released.

2019-08-20 23:35 UTC, TomWFox approved these changes

2019-08-21 11:24 UTC, TomWFox approved these changes

2019-09-03 23:53 UTC, mtrezza commented
Don't merge yet, I think some changed need to be made in the JS SDK as well. Discussion in https://github.com/parse-community/parse-server/issues/5930

2019-09-06 12:49 UTC, mtrezza commented
I've added docs for https://github.com/parse-community/Parse-SDK-JS/pull/910 after changes have been approved. Will that be merged as well or is there another approval round needed?

2019-09-06 13:43 UTC, TomWFox approved these changes
LGMT!

2019-09-06 14:45 UTC, mtrezza commented
Oops, I just deleted the branch by mistake. What should I do now, open a new PR?

2019-09-06 14:45 UTC, mtrezza commented
Ah, it seems to be fine after reopening.

2019-09-07 01:22 UTC, davimacedo approved these changes
LGTM!

2019-09-07 01:22 UTC, merged