Add documentation for the LDAP auth module
ParsePlatform/Docs pull request #685
Opened 2019-11-20 12:44 UTC by brodo

This PR adds documentation for the [LDAP auth module](https://github.com/parse-community/parse-server/pull/6226).

2019-11-20 12:57 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +To build a query which works with your LDAP server, you can use a LDAP client like [Apache Directroy Studio](https://directory.apache.org/studio/).
```suggestion
To build a query which works with your LDAP server, you can use a LDAP client like [Apache Directory Studio](https://directory.apache.org/studio/).
```

2019-11-20 17:11 UTC, dplewis requested changes

2019-11-20 17:11 UTC, dplewis commented on _includes/parse-server/third-party-auth.md
> +
Extra line break

2019-11-20 17:11 UTC, dplewis commented on _includes/parse-server/third-party-auth.md
> +    "dn": "Bind dn. {{id}} is repalced with the id suppied in authData",
{{id}} is replaced with the id supplied in authData.

2019-11-20 17:11 UTC, dplewis commented on _includes/parse-server/third-party-auth.md
> +
Extra line breaks

2019-11-21 18:31 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +
The line breaks are still present 🙂

2019-11-21 22:07 UTC, TomWFox approved these changes
Looks good to me! As standard we’ll wait until the server pr is merged and a release is published before merging the docs pr.

2019-11-26 08:31 UTC, brodo commented
The PR in the other repo is merged now.

2019-11-26 08:33 UTC, TomWFox commented
👍 I’ll wait for a release to merge this.

2020-01-09 09:59 UTC, TomWFox commented
Merging as 3.10 has been released.

2020-01-09 10:00 UTC, TomWFox commented
@brodo could you resolve the merge conflict and then we'll get this in

2020-01-09 23:44 UTC, dplewis approved these changes

2020-01-09 23:45 UTC, merged

2020-01-09 23:46 UTC, TomWFox commented
Thanks @dplewis :)