Update config.md
ParsePlatform/Docs pull request #689
Opened 2019-12-02 19:21 UTC by AugustoAmaral

Just a minor change that can be usefull

2019-12-02 19:32 UTC, TomWFox requested changes
Thanks for making a PR!

Seems like a useful note to add, just a couple minor changes needed.

2019-12-02 19:32 UTC, TomWFox commented on _includes/rest/config.md
> +You can also update the config by sending a `PUT` request to config URL. Here is a simple example that will update the `Parse.Config` (requires masterKey) :
```suggestion
You can also update the config by sending a `PUT` request to config URL. Here is a simple example that will update the `Parse.Config` (requires `masterKey`):
```

2019-12-02 19:32 UTC, TomWFox commented on _includes/rest/config.md
> +If you want to make any changes on configs without sending the masterkey,  you will need to create a cloud function that makes those changes.
```suggestion
If you want to make any changes to configs without sending the `masterkey`, you will need to create a Cloud Function that makes those changes.
```

2019-12-02 23:34 UTC, AugustoAmaral commented
Done

2019-12-03 08:54 UTC, TomWFox approved these changes
Looks good, thanks for contributing!

2019-12-03 08:54 UTC, merged