GraphQL: Add File & LogInWith
ParsePlatform/Docs pull request #702
Opened 2020-01-28 18:34 UTC by Moumouls

Currently available on parse-server:master

2020-01-28 22:48 UTC, TomWFox requested changes

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/files.md
> +## Add a File field to Class
```suggestion
## Add a File field to a Class
```

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/files.md
> +## Create File
```suggestion
## Create a File
```

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/files.md
> +GraphQL API support nested mutation for the `File` type, so you can send the file along the Parse Object or just upload the file and get returned information.
```suggestion
The GraphQL API supports nested mutation for the `File` type, so you can send the file along with the Parse Object or just upload the file and get the returned information.
```

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/files.md
> +Lets create a new `GameScore` object and upload the file along the creation.
```suggestion
Lets create a new `GameScore` object and upload the file.
```

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/users.md
> +You can log in a user via a 3rd party auth system (Custom, Facebook, Twitter, etc...) with the `logInWith` mutation.
```suggestion
You can log in a user via a [3rd party authentication](https://docs.parseplatform.org/parse-server/guide/#supported-3rd-party-authentications) system (Facebook, Twitter, Apple and many more) with the `logInWith` mutation.
```

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/users.md
> +For more information about the use of authData: [AuthData Guide](https://docs.parseplatform.org/parse-server/guide/#supported-3rd-party-authentications)
```suggestion
```

2020-01-28 22:48 UTC, TomWFox commented on _includes/graphql/users.md
> +## 3rd Party Auth
```suggestion
## 3rd Party Authentication
```

2020-02-15 01:11 UTC, TomWFox approved these changes
I’ve applied my changes and I’m happy. @davimacedo do you want to take a look?

I can resolve the bundle.js conflict when merging.

2020-02-17 07:12 UTC, davimacedo approved these changes
It looks good to me. LGTM!

2020-03-02 22:39 UTC, merged