Add keycloak referering to PR #6376 in parse-server
ParsePlatform/Docs pull request #703
Opened 2020-01-28 18:48 UTC by rhuanbarreto

2020-01-28 22:56 UTC, TomWFox requested changes

2020-01-28 22:56 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +The options passed to Parse server:
```suggestion
The options passed to Parse Server:
```

2020-01-28 22:56 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +userinfo oauth call, comparing the attributes
```suggestion
```

2020-01-28 22:56 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +The authentication module will test if the authData is the same as the
```suggestion
The authentication module will test if the authData is the same as the userinfo oauth call, by comparing the attributes.
```

2020-01-28 22:56 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +    "access_token": "access token you got from keycloak JS client authentication",
```suggestion
    "access_token": "access token from keycloak JS client authentication",
```

2020-01-28 22:59 UTC, TomWFox commented
Thanks for contributing!! Just a few small changes needed.

So you’re aware, this won’t be merged until a release of parse Server is made including your pr and I’ve made a final review.

2020-02-15 01:13 UTC, TomWFox approved these changes
Minor suggestion but apart from that this looks good!

2020-02-15 01:13 UTC, TomWFox commented on _includes/parse-server/third-party-auth.md
> +Copy the JSON config file generated on Keycloak ([how-to link](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter))
```suggestion
Copy the JSON config file generated on Keycloak ([tutorial](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter))
```

2020-08-31 10:02 UTC, rhuanbarreto commented
https://github.com/parse-community/parse-server/pull/6376 was approved. You can also merge here.

2020-11-02 17:13 UTC, merged