Deploying on Back4App
ParsePlatform/Docs pull request #739
Opened 2020-06-05 17:20 UTC by alyssoncm

Deploying on Back4App Guideline

2020-06-24 19:27 UTC, alyssoncm commented
Updated @TomWFox

2020-06-29 14:18 UTC, TomWFox requested changes

2020-06-29 14:18 UTC, TomWFox commented on _includes/parse-server/deploying.md
> +{% include_relative _includes/parse-server/deploying-back4app.md.md %}
```suggestion
{% include_relative _includes/parse-server/deploying-back4app.md %}
```

2020-06-29 14:18 UTC, TomWFox commented on _includes/parse-server/deploying-back4app.md
> +1. Create a free [Back4App Account](https://www.back4app.com/)(if you don’t have one already).
```suggestion
1. Create a free [Back4App Account](https://www.back4app.com/).
```

2020-07-01 15:08 UTC, TomWFox approved these changes

2020-07-01 15:08 UTC, merged