Need session activation from Parse
ParsePlatform/Docs pull request #830
Opened 2021-05-31 13:48 UTC by FandryNoutah

After logging in with parseUser, it can be fine if you start session automatically and developers don't need to call PHP session_start() function, or define into the documentation the full use of the session, thanks.

2021-07-20 13:13 UTC, mtrezza commented
@TomWFox Did you request a technical review? This change has errors in style and typos.

2021-07-20 13:17 UTC, TomWFox commented
Hmm, perhaps technical and style. A lack of technical understanding on my part also leaves me unsure of the best style here!

2021-07-26 19:05 UTC, mtrezza commented
@dplewis As I understand it, the developer needs to call `session_start()` to read the session into the `$_SESSION` superglobal, which then becomes available for the Parse to resume the session then initializing the SDK. Do you know why we let the developer do this manually in the PHP SDK instead of doing this automatically?

2021-07-26 19:11 UTC, mtrezza requested changes

2021-07-26 19:11 UTC, mtrezza commented on _includes/php/users.md
> +//Here we need to call session_start() if we want to rerieve the current user
Can you please move the line out of the code block and add it after the sentence above?

> By default, whenever you use any signup or login methods, the user will be saved in PHP Session storage, the `$_SESSION` superglobal. When re-initializing the Parse PHP SDK, you may need to instruct PHP to load the stored session data into the `$_SESSION` superglobal using `session_start()` before initializing the Parse PHP SDK to make continue with the user session.

2021-07-26 19:21 UTC, dplewis commented
@mtrezza I believe that calling `session_start()` multiple times will result in an error being thrown which is probably why we don't include it in the SDK. 

If a developer tries to use persistant storage an error is called
```
'PHP session_start() must be called first.'
```
If a developer only wants to query and such without persistant storage then calling `session_start()` in the SDK will be a performance hit.

A note in the docs is fine, it should have been added a while ago, see
https://github.com/parse-community/parse-php-sdk/issues/41

2021-07-26 20:40 UTC, mtrezza commented
Thanks for that insight, and that you even found https://github.com/parse-community/parse-php-sdk/issues/41. Note is in the docs. We should be good now.

2021-07-26 20:42 UTC, mtrezza approved these changes

2021-07-26 20:42 UTC, merged