docs: Add GraphQL docs for unset field
ParsePlatform/Docs pull request #853
Opened 2021-10-23 14:36 UTC by Moumouls

2021-11-04 12:34 UTC, mtrezza commented
We don't have versioned docs yet, so this has to sit until 5.0 release

2022-03-18 10:27 UTC, Moumouls commented
@mtrezza  this one should also be ok to merge 🙂

2022-03-22 17:50 UTC, mtrezza requested changes

2022-03-22 17:50 UTC, mtrezza commented on _includes/graphql/files.md
> +Lets update a `GameScore` object and unset the file linked on the `screenshot` field. By setting the `screenshot` field to null, the linked file will be removed from the `Gamescore` object.
> Let's

> linked in the `screenshot` field

2022-03-22 17:50 UTC, mtrezza commented on _includes/graphql/files.md
> +**Note:** the file will be not deleted from your file storage.
> The file

2022-03-22 17:50 UTC, mtrezza commented on _includes/graphql/objects.md
> +**Note:** Following the official GraphQL API Specs, setting a field to `null` through the GraphQL API will completly unset the field in the database on the targeted Parse Object. GraphQL API will tra
> Following the official GraphQL API specification, setting a field to `null` will unset the field in the database for the  respective Parse Object. The GraphQL API will transform `null` on the server side before saving the object to correctly unset the field in the database.

Remove `Note:` before the comment, doesn't seem to be necessary.

2022-03-22 17:50 UTC, mtrezza commented on _includes/graphql/objects.md
> +**Additional note:** GraphQL API will always return `null` if the field is `null` or `undefined` in the database. A GraphQL API do not support difference between `null` and `undefined` into the data
> The GraphQL API will return `null` if the field is `null` or `undefined` in the database. The GraphQL API do not differentiate between `null` and `undefined` in the data response.

Remove `Additional note:` before the comment, doesn't seem to be necessary.

2022-11-14 23:48 UTC, Moumouls commented
@mtrezza PR updated, also my VS code has performed a quick lint on the MD.

2022-11-15 02:41 UTC, mtrezza requested changes

2022-11-15 02:41 UTC, mtrezza commented on _includes/graphql/objects.md
> +Across the whole GraphQL API you can simply unset a field by setting his value to `null`.
```suggestion
Across the whole GraphQL API you can simply unset a field by setting its value to `null`.
```

2022-11-15 02:41 UTC, mtrezza commented on _includes/graphql/files.md
> +Let's update a `GameScore` object and unset the file linked in the `screenshot` field. By setting the `screenshot` field to null, the linked file will be removed from the `Gamescore` object.
```suggestion
Let's update a `GameScore` object and unset the file linked in the `screenshot` field. By setting the `screenshot` field to `null`, the linked file will be removed from the `Gamescore` object.
```

2022-11-15 02:41 UTC, mtrezza commented on _includes/graphql/objects.md
> +GraphQL API will always return `null` if the field is `null` or `undefined` in the database. A GraphQL API do not support difference between `null` and `undefined` into the data response.
```suggestion
The GraphQL API will always return `null` if the field is `null` or `undefined` in the database. The GraphQL API does not differentiate between `null` and `undefined` in the data response.
```

2022-12-24 13:53 UTC, Moumouls commented
thanks @mtrezza  for suggested commits tell if we need to adjust other things here 🚀

2022-12-24 16:50 UTC, mtrezza approved these changes
Looks all good, thanks for the fixes, is this ready for merge?

2022-12-25 11:55 UTC, Moumouls commented
@mtrezza ready to merge here :)

2022-12-25 15:07 UTC, merged