feat: defined schema docs
ParsePlatform/Docs pull request #863
Opened 2022-02-20 12:23 UTC by Moumouls

2022-02-20 12:25 UTC, Moumouls commented
@sadortun  if you want to take a look, feel to suggest some commit changes from github UI 🙂

2022-02-20 18:01 UTC, mtrezza requested changes

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +You can set each CLP field with options to add a first strong security layer. This security layer will be applied on the Parse Class and all Parse Objects into this class.
"into this class"? Do you mean sub classes?

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +This CLP key is powerful and need some additional explanation.
I think this line can be removed, it doesn't seem to provide any relevant info. Maybe instead a sentence about what this is (used for).

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +Listed keys under `*` will be protected from all users. Don't worry by default, `authData`, `emailVerified`, `password` are protected.
Remove "don't worry"

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +But here for example we protect `username` from all users. So user A, even authenticated will not be able to get the `username` of a user B.
Where is "here"? There is an example before and one after.

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +But here for example we protect `username` from all users. So user A, even authenticated will not be able to get the `username` of a user B.
The references "user A", "user B" seem to not be used anywhere else? If so, just simplify this to something like "a user cannot ... of other users".

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +But protected fields could be combined for example.
Make this is clear reference, like: "Protected fields ... as in this example:"

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +In this case, a user member of the Parse Role `Admin` will be able to get the `phone` and `score` of another User. A user member of the Parse Role `VerifiedUser` can only get `phone`.
In which case, the example above?

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/core-classes-fields.md
> +Parse will never delete these fields on **ALL** classes if not provided in a class schema
"will never delete the following fields from any class, even if these fields are not defined in a class schema"

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/fields.md
> +You can find here all field types available on Parse
"These field types are available..."

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/fields.md
> +- `Number`: this type support `required` and `defaultValue`
Maybe male this a table? Or at least remove the repetitive terms.

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +Parse Server was historically designed to be a schema less system. You didn't have to perform migration and define specific database schemas at start up time.
"schemaless", "start-up"

Remove "historically", it's confusing (is it still today designed that way?). Instead:
"parse server is designed to be..."

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +But schema less do not fulfill each use case of developers and could also do not play very well with some new Parse Server features like the GraphQL API.
Remove the 2 prose paragraphs, instead simplify to the facts:

"For use cases in which a pre-defined schema is beneficial or required, you can define class fields, indexes, Class Level Permissions and more."

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +To leverage the power of Defined Schema we recommend to setup parse user like an express app.
Rephrase this, is it required or why do we "recommend"?

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/indexes.md
> +To optimize you Parse Server database performance you can define indexes and compound indexes.
"To optimize the Parse Server performance..."

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/indexes.md
> +special notation `_p_myFieldName`.
`_p_<FIELDNAME>`

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/indexes.md
> +Note: Currently Defined Schemas do not support indexes on special `_Join` classes used under the hood by the `Relation` type
Dot at end

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You classes definitions stored in an `Array`.
Could you rephrase this?

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You can set the `strict` option to `true` if you want parse-server to delete removed classes from your schemas from your database. Data stored in removed classes will be lost.
"Parse Server"

Could you rephrase "from your schemas from your database", may be confusing

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/options.md
> +`strict` is default to `false`. If you often change your schemas be aware that you can have some stale classes in your database. You will need to delete these classes manually.
"By default `strict` is `false`.

"You can have stale..." sounds like it's permissible. I think you want to say that the stale classes are unwanted and may remain?

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You can set the `deleteExtraFields` option to `true` if you parse-server to delete removed a class field from your database. Data stored in the removed field will be lost.
"if you want Parse Server to..."

"Delete remove" - a typo?

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/options.md
> +`deleteExtraFields` is default to `false`. Be aware that some stale fields could exists in your database. You will need to delete these fields manually.
Same here rephrasing

2022-02-20 18:01 UTC, mtrezza commented on _includes/defined-schema/options.md
> +A function called before parse-server performs schema updates based on the `definitions` option
Always use "Parse Server" when you refer to the product, don't use "parse-server" unless you are referring to the repository.

2022-02-21 22:19 UTC, sadortun commented on _includes/defined-schema/class-level-permissions.md
> +## CLP Key Options
I would suggest replacing globally `key` with either `parameter` or `attribute` depending on the context.

Currently `parameter` seems to be more generalized as config keys

https://docs.parseplatform.org/parse-server/guide/#usage

2022-02-21 22:19 UTC, sadortun commented on _includes/defined-schema/getting-started.md
> +    deleteExtraFields: true,
Theses 2 parameters should be `false` by default in the example to avoir a user copy-pasting the example config have it's data deleted unintentionally.

2022-03-05 09:37 UTC, Moumouls commented
@sadortun  @mtrezza  requested changes performed. Feel free to use the Github commit suggestion feature if you some new changes suggestions, then i can apply easily your changes :)

2022-03-05 17:36 UTC, sadortun reviewed
Excellent! 

Only thing could be to add some Bold/red font on dangerous options

2022-03-05 17:36 UTC, sadortun commented on _includes/defined-schema/options.md
> +`recreateModifiedFields` is default to `false`. Be aware that if you do not perform some data migration, you can result with data type inconsistency on modified field.
Maybe adding some Bold for ?

**Be aware that if you do not perform some data migration**

2022-03-18 10:26 UTC, Moumouls commented
@sadortun  i added bold, @mtrezza  since Parse V5 was released, what do you think about merging this one ?

2022-03-24 17:36 UTC, mtrezza requested changes
General feedback: the texts are quite verbose. Try to condense essential information into few words. Try to use as few lines as possible, instead of many lines with only a few words per line, that makes it easier to read and uses less space. For example:

```
// Here your Parse Server is ready
// with schemas up to date

// Just a code example if you want to expose
// an endpoint when parse is fully initialized
```
can be condensed into
```
// Parse Server is ready with up-to-date schema
```

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +- `{}`: if you set the CLP key with `{}` like `create: {}` only calls with your Parse Server Master Key will have the permission
"\`role:\<roleName\>\`: If you are making use of Parse Roles you can set the permission based on a role."
...
"If you set the CLP key to \`{}\`" ... "calls with the Parse Server master key will"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +- `requiresAuthentication`: If true an authenticated user will have the permission.
"If set to \`true\`, only authenticated users"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +- `requiresAuthentication`: If true an authenticated user will have the permission.
"If set to \`true\`, only authenticated users"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +We will take the Parse User Class as example.
"as an example:"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +We will take the Parse User Class as example.
"as an example."

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +But in the above example we protect `username` from all users. So a Parse User, even authenticated will not be able to get the `username` of a another Parse User.
Remove next line between the 2 sentences.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +But in the above example we protect `username` from all users. So a Parse User, even authenticated will not be able to get the `username` of a another Parse User.
Remove next line between the 2 sentences.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +`protectedFields` could be also combined as in the following example.
"following example:"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +`protectedFields` could be also combined as in the following example.
"following example:"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +In the example above, a Parse User member of the Parse Role `Admin` will be able to get the `phone` and `score` of another Parse User. A Parse User member of the Parse Role `VerifiedUser` can only ge
" A Parse User who is member of the Parse Role"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/class-level-permissions.md
> +In the example above, a Parse User member of the Parse Role `Admin` will be able to get the `phone` and `score` of another Parse User. A Parse User member of the Parse Role `VerifiedUser` can only ge
" A Parse User who is member of the Parse Role"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/core-classes-fields.md
> +Parse will never delete these fields on **ALL** classes if not provided in a class schema
still open

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/fields.md
> +`required`: `boolean`, by default false. Force the field to be set on create and update.
"by default \`false\`."

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/fields.md
> +`required`: `boolean`, by default false. Force the field to be set on create and update.
", forces the field to be set on create and update, is \`false\` by default."

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // Special _p_ word to create indexes on pointer fields
"// The special prefix \_p\_ is used to create indexes on pointer fields"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // Special _p_ word to create indexes on pointer fields
"// Special _p_ prefix"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // Empty object meas that only master key
write comment on 1 line instead of 2

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // Empty object meas that only master key
write comment on 1 line instead of 2

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +  // Then just register schemas into Parse Server
// Define schemas of Parse Server

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +  // Then just register schemas into Parse Server
// Define schemas of Parse Server

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // Parse Schema API will be disabled
// Disable Parse Schema API; if you need to update the schemas later
// you need to redeploy Parse Server with the new schema definition

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // Parse Schema API will be disabled
// If set to \`true\`, the Parse Server API for schema changes is disabled and schema
// changes are only possible by redeploying Parse Server with a new schema definition

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // If true, Parse Server will delete non defined Classes from
// If set to \`true\`, Parse Server will automatically delete non-defined classes from
// the database; internal classes like \`User\` or \`Role\` are never deleted.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // If true, Parse Server will delete non defined Classes from
// Parse Server will automatically delete non-defined classes from the
// database; internal classes like \`User\` or \`Role\` are never deleted.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    recreateModifiedFields: false,
// If set to \`true\`, a field type change will cause the field including its data to be
// deleted from the database, and then a new field to be created with the new type

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    recreateModifiedFields: false,
// If set to \`true\`, a field type change will cause the field including all of its data
// being deleted from the database and then recreate the field with the new type

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    deleteExtraFields: false,
// If set to \`true\`, Parse Server will automatically delete non-defined class fields;
// internal fields in classes like `User` or `Role` are never deleted.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    deleteExtraFields: false,
// If set to \`true\`, Parse Server will automatically delete non-defined class fields.
// internal fields in classes like `User` or `Role` are never deleted.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    parseServer.expressApp.get("/ready", (req: any, res: any) => {
// Parse Server is ready with up-to-date schema

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    parseServer.expressApp.get("/ready", (req: any, res: any) => {
Replace whole comment block with:

// Parse Server is ready with up-to-date schema

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/indexes.md
> +To define an index on a `Pointer` field you need to use a
Reformat and reword to:

To optimize the Parse Server performance you can define indexes and compound indexes. Parse Server does not support indexes on special `_Join` classes used under the hood by the `Relation` type.

To define an index on a `Pointer` field you need to use the special notation `_p_<FIELDNAME>`. For example, if you define `city: { type: "Pointer", targetClass: "City" }` in your `fields` you can define an index on this pointer with `cityIndexExample: { _p_city: true }`.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/indexes.md
> +To define an index on a `Pointer` field you need to use a
Reformat and reword to:

To optimize the Parse Server performance you can define indexes and compound indexes. Parse Server does not support indexes on special `_Join` classes used under the hood by the `Relation` type.

To define an index on a `Pointer` field you need to use the special notation `_p_<FIELDNAME>`. For example, if you define `city: { type: "Pointer", targetClass: "City" }` in your `fields` you can define an index on this pointer with `cityIndexExample: { _p_city: true }`.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You can set the `recreateModifiedFields` option to `true` if you want Parse Server to clean field data before Parse Server update the field type when you change the type of a field (ie: from `String`
"before updating the field type when you change the field type, for example from `String` to `Number`. Data stored under the modified"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You can set the `recreateModifiedFields` option to `true` if you want Parse Server to clean field data before Parse Server update the field type when you change the type of a field (ie: from `String`
"before updating the field type when you change the field type"

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +`recreateModifiedFields` is default to `false`. **Be aware that if you do not perform some data migration, you can result with data type inconsistency on modified field.**
\`recreateModifiedFields\` defaults to \`false\`.

The "Be aware" comment could be unclear for readers, could you rephrase that? What is "some data migration"? In which cases does the user have to be aware, if the field is true of false?

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +`recreateModifiedFields` is default to `false`. **Be aware that if you do not perform some data migration, you can result with data type inconsistency on modified field.**
\`recreateModifiedFields\` defaults to \`false\`

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +On production a good practice could be to create a new field with your new type, and then create a Parse Cloud Job to migrate old field data to the new created field.
"Good practice would be to create the new field of the new type" ... "to the newly created field."

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +On production a good practice could be to create a new field with your new type, and then create a Parse Cloud Job to migrate old field data to the new created field.
"Good practice would be to create a new field with a new type" ... "to the newly created field."

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You can set the `lockSchemas` option to `true` if you want to to prevent any `Parse.Schema` manipulation outside of the Defined Schema feature. If this options is `true` any create/update/delete requ
"if you want to prevent any schema manipulation and to lock the schema as defined in the Parse Server configuration." ... "any create, update and delete request will be denied by the Parse Server API, even with the master key."

You can delete the following sentence "This option help to keep " as it does not provide any additional information.

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +You can set the `lockSchemas` option to `true` if you want to to prevent any `Parse.Schema` manipulation outside of the Defined Schema feature. If this options is `true` any create/update/delete requ
"if you want to prevent any schema manipulation and to lock the schema as defined in the Parse Server configuration."

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +A function called before parse-server performs schema updates based on the `definitions` option
still open

2022-03-24 17:36 UTC, mtrezza commented on _includes/defined-schema/options.md
> +A function called before parse-server performs schema updates based on the `definitions` option
still open

2022-05-02 14:55 UTC, stephannielsen commented
Maybe not the best place to ask but as there is no official documentation available yet:

* Can we define on schema levels Array of Pointers of a specific class? This PR does not mention this and from some tests it seems that if you specify `Array` as type in the schema, anything is accepted as array content.
* It would be nice if the documentation could include some examples on how to use `beforeMigration` and `afterMigration` hooks. I am not sure how I could leverage them to do migrate data.

2022-05-02 16:17 UTC, mtrezza commented
Thanks for the feedback to the docs, maybe @Moumouls can add this to the PR?
To your first point, the best place to ask is our [community forum](https://community.parseplatform.org).

2022-05-02 16:26 UTC, Moumouls commented
thanks, @stephannielsen  for your feedback I'll quickly answer to your question. Parse is not currently able to type the content of `Array`. Anything could be stored in the `Array`. You can use the beforeSave Parse Cloud hook to prevent users to save something than desired pointers.

If you use the GraphQL API. You can use the "inline fragment" graphql feature to automatically get data from the pointer array. 

https://community.parseplatform.org/t/type-arrayresult-must-have-a-selection-of-subfields-error/847/2?u=moumouls

for example `... on MyPointerClass { id aField}`

2022-05-02 19:16 UTC, stephannielsen commented
Thanks @Moumouls and @mtrezza  for your quick replies.

I already expected that Parse can't type array fields and that triggers would allow me to validate incoming data. Thanks for the quick confirmation.

2022-05-12 07:57 UTC, RahulLanjewar93 commented
Hey, just had a quick question, since the documentation isn't updated yet. Can we have unique indexes according to the recent merge?

Thanks.

2022-05-12 09:59 UTC, mtrezza commented
If anyone wants to pick up and finish this PR (see the review comments, just grammar and style corrections), please feel free to do so, so we can merge this chapter about defined schema into the docs. You will probably have to open a new PR, then we can close this one.

2022-11-14 23:38 UTC, Moumouls commented
@mtrezza  any chance to update your comments using the commit suggestion feature ? then I'll be happy to apply all your suggestions 🚀

2022-12-24 13:52 UTC, Moumouls commented
closing in favor of https://github.com/parse-community/docs/pull/912

2022-12-24 13:52 UTC, closed without merging