feat: defined docs
ParsePlatform/Docs pull request #912
Opened 2022-12-24 13:47 UTC by Moumouls

2022-12-24 13:50 UTC, Moumouls commented
@mtrezza here the final PR updated with lockfile V2

2022-12-24 16:53 UTC, mtrezza requested changes

2022-12-24 16:53 UTC, mtrezza commented on _includes/defined-schema/getting-started.md
> +    // authorized to manage cities
```suggestion
    // Only a user linked to the Admin Parse Role is authorized to manage cities
```

2022-12-24 16:54 UTC, mtrezza commented
Other than the comment above, is this ready for merge?

2022-12-24 20:24 UTC, sadortun approved these changes
Excellent work ! 🚀

2022-12-25 00:16 UTC, Moumouls commented
Ready for merge @mtrezza  !

2022-12-25 02:14 UTC, merged