feat: add rate limit docs
ParsePlatform/Docs pull request #926
Opened 2023-04-14 03:53 UTC by dblythy

Closes #925

2023-04-14 09:20 UTC, mtrezza commented on _includes/common/security.md
> +* Available only on parse-server starting 6.0.0 *
```suggestion
* Available on Parse Server >= 6.0.0 *
```

2023-04-14 09:50 UTC, mtrezza requested changes

2023-04-14 09:50 UTC, mtrezza commented on _includes/common/security.md
> +- `redisUrl` Optional, the URL of the Redis server to store rate limit data.
```suggestion
It's important to restrict how often a client can call the Parse Server API. This prevents malicious attacks that could:
- overwhelm server resources by exceeding expected API traffic
- collect large amounts of data ("data scraping")
- repeatedly guess passwords, object IDs, installation IDs or other data ("brute force")

Parse Sever offers a mechanism to enforce rate limits by setting the Parse Server option `rateLimit`, or by specifying a `rateLimit` object on a Cloud Function validator.

The valid options for a rate limit are:

- `requestPath`: The path of the API route to be rate limited.
- `requestMethods`: Optional, the HTTP request methods to be rate limited.
- `requestTimeWindow`: The window of time in milliseconds within which the number of requests set in `requestCount` can be made before the rate limit is applied.
- `requestCount`: The number of requests that can be made per IP address within the time window set in `requestTimeWindow` before the rate limit is applied.
- `errorResponseMessage`: The error message that should be returned in the body of the HTTP 429 response when the rate limit is hit. Default is `Too many requests.`.
- `includeInternalRequests`: Optional, whether the rate limit will also apply to requests that are made in by Cloud Code.
- `includeMasterKey`: Optional, whether the rate limit will also apply to requests using the `masterKey`
- `redisUrl` Optional, the URL of the Redis server to store rate limit data.
```

2023-04-14 09:50 UTC, mtrezza commented on _includes/common/security.md
> +
```suggestion
> ⚠️ Rate limits should be enforced as far away from Parse Server as possible to mitigate possible impacts on resource costs, availability and integrity. While Parse Server offers a rate limiting mechanism as a conveniently available security feature without requiring a deep level of expertise, it is *not considered best practice* to enforce rate limits only after requests already reached the server. For better protection we advice to examine your network architecture an consider enforcing rate limits on the outer edge of the cloud if using a content delivery network, or at least before requests reach the server resource. Consult your cloud service provider for recommended rate limit and firewall solutions for your resources.

```

2023-05-25 21:42 UTC, mtrezza approved these changes
Looks good! Is this ready for merge?

2023-05-27 12:34 UTC, dblythy commented
Yep!

2023-05-27 12:35 UTC, merged